services:
  crdb-lb:
    image: haproxy:3.0
    container_name: crdb-lb
    hostname: crdb-lb
    ports:
      - "26257:26257"
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    restart: always
    links:
      - us-east
      - us-central
      - us-west

  us-east:
    image: cockroachdb/cockroach:${CRDB_VERSION}
    platform: linux/arm64
    container_name: us-east
    hostname: us-east
    volumes:
      - node1:/cockroach/cockroach-data
      - ./settings:/cockroach/settings:ro
    command: |
      bash -c 'exec cockroach start \
        --insecure \
        --store=/cockroach/cockroach-data \
        --max-sql-memory=512MiB \
        --cache=512MiB \
        --listen-addr=us-east:26257 \
        --http-addr=0.0.0.0:8080 \
        --join=us-east:26257,us-central:26257,us-west:26257 \
        --locality="region=East US,zone=east" \
        --enterprise-encryption="$(cat /cockroach/settings/encryption-options.cfg)"'
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535

  us-central:
    image: cockroachdb/cockroach:${CRDB_VERSION}
    platform: linux/arm64
    container_name: us-central
    hostname: us-central
    volumes:
      - node2:/cockroach/cockroach-data
      - ./settings:/cockroach/settings:ro
    command: |
      bash -c 'exec cockroach start \
        --insecure \
        --store=/cockroach/cockroach-data \
        --max-sql-memory=512MiB \
        --cache=512MiB \
        --listen-addr=us-central:26257 \
        --http-addr=0.0.0.0:8080 \
        --join=us-east:26257,us-central:26257,us-west:26257 \
        --locality="region=Central US,zone=central" \
        --enterprise-encryption="$(cat /cockroach/settings/encryption-options.cfg)"'
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535

  us-west:
    image: cockroachdb/cockroach:${CRDB_VERSION}
    platform: linux/arm64
    container_name: us-west
    hostname: us-west
    volumes:
      - node3:/cockroach/cockroach-data
      - ./settings:/cockroach/settings:ro
    command: |
      bash -c 'exec cockroach start \
        --insecure \
        --store=/cockroach/cockroach-data \
        --max-sql-memory=512MiB \
        --cache=512MiB \
        --listen-addr=us-west:26257 \
        --http-addr=0.0.0.0:8080 \
        --join=us-east:26257,us-central:26257,us-west:26257 \
        --locality="region=West US,zone=west" \
        --enterprise-encryption="$(cat /cockroach/settings/encryption-options.cfg)"'
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
  init:
    image: cockroachdb/cockroach:${CRDB_VERSION}
    platform: linux/arm64
    container_name: init
    depends_on:
      - us-east
      - us-central
      - us-west
    command: ["init", "--insecure", "--host=us-east"]

volumes:
  node1:
  node2:
  node3: